### ISSUE TITLE
cron-Jobs unterstützen

### ISSUE THREAD

**Issue by tomgk** [microservice-test-exolin/maven-service-plugin#18]
Grundkonfiguration:
* Name
* optionale Beschreibung
* optionaler Service-bezug

### Aufruf einer URL
Config:
* URL
* ggf. Request-Header und/oder Auth

### Aufruf eines Bash-Scripts

Config
* Bashscript-Inhalt

im Bash-Script sollten Environment-Variablen esetzt werden die nützlich sein könnten
* Name des Services (falls im Kontext eines Services)
* Pfade vom Service (falls im Kontext eines Services)

### Aufruf eines Programms
Quasi single-line Bash Script

### Aufruf einer Service-Logik
Config
* Name des Services
* Name der aufzurufenden Main-Klasse
* an Main-Klasse zu übergebende Parameter

## Abschluss
Wenn umgesetzt sollte
* ein Issue zur Anzeige in der Web-UI erstellt werden
* der Inhalt in ein Markdown-File für Dokumentation rein

**Comment by tomgk** [comment]
```yml
cron:
- name: Example with URL
  url: /update
  schedule: every 2 hours
- name: Example with Bash
  script: |
    echo A
    echo B
  schedule: every day
- name: Example with Service main class
  mainClass: x.y.z.Main
  arguments:
  - val1
  - val2
```
